# Generated by Django 5.0.2 on 2024-08-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=250, null=True)),
                ('key', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=250, null=True)),
                ('key', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='qustion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qstion', models.CharField(max_length=250, null=True)),
                ('key', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
