# Generated by Django 5.0.2 on 2024-08-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_answer_options_qustion_delete_mymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='options',
            new_name='optionAnser',
        ),
    ]
