# Generated by Django 5.0.2 on 2024-08-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_options_optionanser'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='unicid',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='optionanser',
            name='unicid',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='qustion',
            name='unicid',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
