# Generated by Django 5.0.2 on 2024-08-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_answer_unicid_optionanser_unicid_qustion_unicid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testkey', models.CharField(max_length=250, null=True)),
                ('qustion', models.CharField(max_length=250, null=True)),
                ('uanswer', models.CharField(max_length=250, null=True)),
                ('answers', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
