# Generated by Django 5.0.2 on 2024-08-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_testanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswer',
            name='crect',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
