# Generated by Django 5.0.2 on 2024-09-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_testanswer_crect'),
    ]

    operations = [
        migrations.CreateModel(
            name='cmuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unames', models.CharField(max_length=250, null=True)),
                ('upass', models.CharField(max_length=250, null=True)),
                ('umail', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
