# Generated by Django 5.0.2 on 2024-09-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_cmuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250, null=True)),
                ('unicid', models.CharField(max_length=250, null=True)),
                ('user', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
