# Generated by Django 5.0.2 on 2024-09-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='crct',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tests',
            name='testids',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tests',
            name='totalq',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
